name: build-and-test_5

on: push

jobs:

  buildandtest:

    name: Build and test the program

    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
      - name: Build_LR_5
        run: |
          cd Lab5/
          make LR_5_Test 
          ./LR_5_Test
          
