LR_5_Test: LR_5.cpp LR_5_Test.cpp list.cpp Unit1.cpp
	g++ LR_5.cpp LR_5_Test.cpp list.cpp Unit1.cpp -ansi -o LR_5_Test -Dmain=_main -Dmain=_AddToListString -Dmain=_AddToListLLong -Dmain=_ReshetoErat

