main: main.cpp list.h stack.h bintree.h 
	g++ main.cpp list.h stack.h bintree.h -Wall -pedantic -o main
	./main
test: LR_6_Test.cpp list.h stack.h bintree.h  
	g++ LR_6_Test.cpp list.h stack.h bintree.h  -Wall -pedantic -Dmain=_main -o test
	./test