name: build-and-test

on: push
paths:
- 'Lab1/**'
jobs:

  buildandtest:

    name: Build and test the program

    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build_Lr_1
        run: |
          cd Lab1/
          make LR_1_Test 
          ./LR_1_Test

      
