name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make main
      working-directory: ./lab7
      run: make test
    - name: Codecov
      run: export CODECOV_TOKEN="be7e8561-c637-4eee-9711-1c8c02adae0c" && bash <(curl -s https://codecov.io/bash)
