name: build-and-test

on: push

jobs:

  buildandtest:

    name: Build and test the program

    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build_LR_2_1
        run: |
          cd Lab2/Lab2_1/
          make LR2_1_Test 
          ./LR2_1_Test
          cd ../Lab2_2  
          make LR2_2_Test 
          ./LR2_2_Test
